### ISSUE TITLE
What's the first gateway to implement?

### ISSUE THREAD

**Issue by gwmoura** [MarcusMann/PayGo-Gateway#2]
* PagSeguro
* Moip
* Mercado Pago
* Paypal

**Comment by marcuxyz** [comment]
1. Mercado Pago
2. Moip
3. Pagseguro

4. Paypal already exist.

**Comment by raulinoneto** [comment]
I vote with @MarcusMann 

1. Mercado Pago
2. Moip
3. Pagseguro

**Comment by alexandresgf** [comment]
MP > PagSeguro > Moip

**Comment by marcuxyz** [comment]
Closing. MercadoPago Selected!
