### ISSUE TITLE
Idioma do Projeto ( Project Language )

### ISSUE THREAD

**Issue by marcuxyz** [MarcusMann/PayGo-Gateway#5]
Pessoal, meus amigos e eu estamos percebendo que algumas pessoas não tem familiaridade com o idioma inglês, tendo isso em mente, estamos iniciando uma votação para decidir qual o idioma devemos aplicar.

Inglês ou Português ( Brasil ).

Lembrando que serverá apenas para:

- Issues
- Pull Request
- Commits

O código será feito em inglês mesmo, isso inclui, métodos, estruturas e etc...

**Comment by raulinoneto** [comment]
Em minha opinião, aplicando o inglês ajudará o pessoal que não tem costume a usar o idioma e, assim, aumentando o know how dela.

**Comment by alexandresgf** [comment]
Full english

**Comment by andrewsmedina** [comment]
+1 for English

**Comment by marcuxyz** [comment]
Closing, chosen English language.
