### ISSUE TITLE
Directory structure proposal for mercado

### ISSUE THREAD

**Issue by raulinoneto** [MarcusMann/PayGo-Gateway#6]
Reading and studing [Mercado Pago API Reference](https://www.mercadopago.com.br/developers/pt/reference) I organized a propose of directory structure for this project, may I was verbose and create so much paths, but I want your opnions. Thanks regards.

    .
    ├── config                  
    │   └── mercadopago.config.yaml                         # API Client configuration for mercadopago                
    ├── docs                                                # Documentation files
    ├── src                                                 # Source files
    │   └── mercadopago                                     # Path of mercadopago methods
    │       ├── customers 
    │       │   ├── customers.go                            # Create, Read and List customers methods.
    │       │   └── customers_test.go
    │       ├── cards
    │       │   ├── cards.go                                # CRUD from client cards
    │       │   └── cards_test.go
    │       ├── identification_types
    │       │   ├── identification_types.go                 # Get document types
    │       │   └── identification_types_test.go
    │       ├── invoices
    │       │   ├── invoices.go                             # Get invoices
    │       │   └── invoices_test.go
    │       ├── merchant_orders
    │       │   ├── merchant_orders.go                      # Create, Get and Update orders
    │       │   └── merchant_orders_test.go
    │       ├── payment_methods
    │       │   ├── payment_methods.go                      # Get payments methods
    │       │   └── payment_methods_test.go
    │       ├── payments
    │       │   ├── payments.go                             # Create, Get, Update and Search payments
    │       │   └── payments_test.go
    │       ├── preferences
    │       │   ├── preferences.go                          # Create, Read and Update preferences
    │       │   └── preferences_test.go
    │       ├── mercadopago.go                              # Expose all methods for API Client and set configs
    │       └── mercadopago_test.go
    ├── main.go
    ├── LICENSE
    └── README.md

**Comment by gwmoura** [comment]
@raulinoneto you can create a PR with this struct, I liked!

**Comment by marcuxyz** [comment]
Thanks for work. My vote is yes

**Comment by alexandresgf** [comment]
Pretty good!

**Comment by gwmoura** [comment]
@MarcusMann you can close this issue too

**Comment by marcuxyz** [comment]
@gwmoura Yeah, i'll clouse 👍
