### ISSUE TITLE
[Votation Propose] What dependecies manager we'll should use?

### ISSUE THREAD

**Issue by raulinoneto** [MarcusMann/PayGo-Gateway#7]
1. dep
2. vgo
3. govendor
4. other

**Comment by gwmoura** [comment]
@raulinoneto I belive a better option is `dep`.

:+1:  for `dep`

**Comment by marcuxyz** [comment]
VGO

**Comment by alexandresgf** [comment]
dep

**Comment by andrewsmedina** [comment]
vgo was accepted as the offical Go version control system.

I believe that makes no sense use another tool.

**Comment by gwmoura** [comment]
I need to update me :/

:+1:  to vgo

@MarcusMann you can close this issue, as @andrewsmedina talked is not sense use another tool

**Comment by marcuxyz** [comment]
@gwmoura I'm sure of that. 
Pr added #10
